version: "3.8"

services:
  tele-bot-manager:
    image: oven/bun:latest
    container_name: tele-bot-manager
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./.env:/app/.env
    entrypoint: ["sh", "-c" , "bun install && bun run bot.ts"]
